posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length 

class PostForm(FlaskForm):
    title = TextAreaField('Title', validators=[DataRequired(), Length(min=1, max=50)])
    content = TextAreaField('Content', validators=[DataRequired()])
    image_file = FileField('Image', validators=[DataRequired(), FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    content = TextAreaField('Comment', validators=[DataRequired(), Length(min=1, max=150)])
    submit = SubmitField('Post')

main/routes.py
from flask import render_template, request, Blueprint
from instagram.models import Post
from instagram.posts.forms import CommentForm
from instagram.users.forms import SearchForm

main = Blueprint('main', __name__)

@main.route("/")
@main.route('/home', methods=['POST', 'GET'])
def home():
    comment = CommentForm()
    form = SearchForm()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts, comment=comment, form=form)

@main.route("/about")
def about():
    form = SearchForm()
    return render_template('about.html', title='About', form=form)

posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from instagram import db
from instagram.models import Post, Comment, Like
from instagram.posts.forms import PostForm, CommentForm
from instagram.posts.utils import save_picture_p

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        picture_file = save_picture_p(form.image_file.data)
        post = Post(title=form.title.data, content=form.content.data, user_id=current_user.id, image_file=picture_file)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route("/post/<int:post_id>")
def post(post_id):
    form = CommentForm()
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post, form=form)

@posts.route('/post/<int:post_id>/update', methods=["POST", "GET"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.image_file = save_picture_p(form.image_file.data)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
        form.image_file.data = post.image_file
    return render_template("create_post.html", title="Update Post", form=form, legend="Update Post")

@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if post.author != current_user:
        abort(403)
    comments = Comment.query.filter_by(post_id=post_id).all()
    likes = Like.query.filter_by(post_id=post.id).all()

    for comment in comments:
        db.session.delete(comment)
    for like in likes:
        db.session.delete(like)

    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')

    return redirect(url_for('main.home'))

@posts.route("/create-comment/<post_id>", methods=["POST"])
@login_required
def create_comment(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        post = Post.query.filter_by(id=post_id).first()
        if post:
            comment = Comment(content=form.content.data, user_id=current_user.id, post_id=post_id, user=current_user)
            db.session.add(comment)
            db.session.commit()
            flash('Comment added Successfully.', category='success')
        else:
            flash('Post does not exist.', category='error')
    else:
        flash('Comment cannot be empty.', category='error')
    return redirect(request.referrer)

@posts.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()
    if not comment:
        flash('comment does not exist.', category='error')
    elif current_user.id != comment.user_id:
        flash('You do not have permission.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()
    return redirect(request.referrer)

@posts.route('/like-post/<post_id>', methods=['GET'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id).first()
    like = Like.query.filter_by(user_id=current_user.id, post_id=post_id).first()
    if not post:
        flash('Post does not exist.', category='error')
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(user_id=current_user.id, post_id=post_id)
        db.session.add(like)
        db.session.commit()
    return redirect(request.referrer)

users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from instagram import db, bcrypt
from instagram.models import User, Post
from instagram.users.forms import SearchForm, RegistrationForm, LoginForm, UpdateAccountForm
from instagram.posts.forms import CommentForm
from instagram.users.utils import save_picture

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check email and password', 'danger')     
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/user/<string:username>')
def profile(username):
    form = CommentForm()
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page)
    return render_template('profile.html', user=user, posts=posts, form=form, title=f"profile - {username}", comment=form)

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    comment = CommentForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.bio.data = current_user.bio
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    page = request.args.get('page', 1, type=int)
    user = current_user
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page)
    return render_template('account.html', title='Account', image_file=image_file, comment=comment, posts=posts, user=user, form=form)
    
@users.route('/search', methods=['POST'])
def search():
    form = SearchForm()
    users = User.query
    if form.validate_on_submit():
        users = users.filter(User.username.ilike('%' + form.searched.data + '%'))
        searched = form.searched.data
    else:
        flash('No results')
    return render_template("search.html", form=form, users=users, searched=searched)

templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="card shadow mb-4">
    <div class="card-body">
      <h5 class="card-title text-center font-weight-bold mb-4">About</h5>
      <p class="card-text text-justify">Instagram is a platform where you can share pictures and see pictures by other users.</p>
      <ul>
        <p>Contacts</p>
        <li>Email: eric.pungho.lee@gmail.com</li>
        <li>GitHub: <a href='https://github.com/ericpungholee'>https://github.com/ericpungholee</a></li>
      </ul>
    </div>
  </div>
{% endblock content %}  

templates/account.html
{% extends "layout.html" %}
{% block content%}
<div class="media text-center">
    <div class="media-body">
        <h2 class="mt-0 accounting-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
    </div>
</div>
<div class="card d-flex align-items-center">
    <div class="card-body d-flex align-items-center">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-row">
                    <label class="col-form-label">{{ form.username.label }}</label>
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-row">
                    <label class="col-form-label">{{ form.email.label }}</label>
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-row">
                    <label class="col-form-label">{{ form.bio.label }}</label>
                    {% if form.bio.errors %}
                        {{ form.bio(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for bio in form.bio.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.bio(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-row align-items-center">
                    <img class="mr-3 rounded-circle article-img img-fluid" src="{{ image_file }}" alt="user profile picture">
                    <div class="col-auto">
                        <label class="col-form-label">{{ form.picture.label }}</label>
                        {{ form.picture(class="form-control-file") }}
                        <small>Please make sure the file type is either jpg or png.</small>
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary")}}
            </div>
        </form>
    </div>
</div>

{% for post in posts.items %}
<div class="container mt-5">
  <div class="row">
      <div class="col-md-8 offset-md-2">
          <div class="card" style="margin-bottom: 20px;">
              <div class="card-header bg-primary text-white">
                  <img class="rounded-circle article-img img-fluid" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                  <h3><a style="color: white;" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h3>
                  <a class="mr-2 text-white" href="{{ url_for('users.profile', username=post.author.username) }}" width="200" height="200">{{ post.author.username }}</a>
                  <small class="mr-2 text-white">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
              </div>
                  <div class="card-body">
                      <div class="d-flex justify-content-between align-items-center">
                          <div>
                              {{ post.likes|length }}
                              {% if current_user.id in post.likes|map(attribute="user_id")|list %}
                                  <a href="/like-post/{{post.id}}"><i class="fas fa-thumbs-up"></i></a>
                              {% else %}
                                  <a href="/like-post/{{post.id}}"><i class="far fa-thumbs-up"></i></a>
                              {% endif %}
                          </div>
                          <div>
                              <a class="mr-2 text-primary" href="{{ url_for('users.profile', username=post.author.username) }}" width="200" height="200">{{ post.author.username }}</a>
                          </div>
                      </div>
                      
                      <img src="{{ url_for('static', filename='post_images/' + post.image_file) }}" width="100%" height="auto" alt="">
                      
                      <br/>

                      <p class="card-text">{{ post.content }}</p>
                      <div class="collapse" id="comments-{{post.id}}">
                          <div class="card">
                              <div class="card-body" id="comments-expanded-{{ post.id }}">
                                  {% for comment in post.comments %}
                                      <div class="d-flex justify-content-between align-items-center">
                                          <div class="w-75">
                                              <a href="{{ url_for('users.profile', username=comment.user.username) }}">{{ comment.user.username }}</a>: {{ comment.content }}
                                          </div>
                                          <div class="w-25 d-flex justify-content-end">
                                              <small class="text-muted">
                                                  {{ comment.date_posted.strftime('%Y-%m-%d') }}
                                              </small>
                                          </div>
                                      </div>
                                      <hr>
                                  {% endfor %}
                              </div>
                          </div>
                      </div>
                     
                      <p class="card-text">
                        {% if post.comments|length > 0 %}
                            <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
                                <small>View {{post.comments|length}} Comments</small>
                            </a>
                        {% else %}
                            <small class="text-muted">No Comments</small>
                        {% endif %}
                    </p>
                    <form method="POST" action="{{ url_for('posts.create_comment', post_id=post.id) }}" class="mx-auto w-50" style="width: 100%; max-width: 500px; margin: 0 auto;">
                      {{ comment.hidden_tag() }}
                      <div class="form-group">
                          {% if comment.content.errors %}
                          {{ comment.content(class="form-control is-invalid") }}
                          <div class="invalid-feedback">
                              {% for error in comment.content.errors %}
                              <span>{{ error }}</span>
                              {% endfor %}
                          </div>
                          {% else %}
                            {{comment.content(class="form-control") }}
                          {% endif %}
                      </div>
                      <button type="submit" class="btn btn-primary">Comment</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}


{% endblock content%}

templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="style.css">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <link rel="stylesheet" href="style.css">
  <script src="https://kit.fontawesome.com/999ca2bb93.js" crossorigin="anonymous"></script>

    
    {% if title %}
      <title>Instagram - {{ title }}</title>
    {% else %}
      <title>Instagram</title>
    {% endif %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('main.home')}}">Instagram</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.about')}}">About</a>
          </li>
        {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('posts.new_post')}}">Post</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.register')}}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
          </li>
        {% endif %}
      </ul>
        <form method="POST" action="{{url_for('users.search')}}" class="form-inline my-2 my-lg-0">
          {{ form.hidden_tag() }}
          <input class="form-control me-2" type="search" placeholder="Search User" aria-label="Search", name="searched">
          <button class="btn btn-outline-secondary" type="submit">
            <i style="color: rgb(21, 127, 234);" class="fas fa-search"></i>
          </button> 
        </form>
      </div>
    </nav>
    {% block content %}{% endblock %}
    <script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
  crossorigin="anonymous"
  ></script>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container mt-5">
    <form method="POST" action="" class="mx-auto w-50">
        {{ form.hidden_tag() }}
        <fieldset>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <div>
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <div>
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor%}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control") }}
                    {% endif %}
                </div>
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small style="padding: 10px;">
      Need An Account? <a class="ml-2 text-primary" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

templates/post.html
{% extends "layout.html" %}
{% block content %}

<article class="media content-section d-flex flex-column justify-content-between h-100">
  <div class="d-flex align-items-center mb-3">
    <img class="rounded-circle article-img mr-3" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="Profile picture">
    <div class="article-metadata">
      <a class="font-weight-bold" href="{{ url_for('users.profile', username=post.author.username) }}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
  </div>
  <h2 class="article-title mb-3" style="word-wrap: break-word; word-break: break-word;">{{ post.title }}</h2>

  
    {{ post.likes|length }}
    {% if current_user.id in post.likes|map(attribute="user_id")|list %}
      <a href="/like-post/{{post.id}}"><i class="fas fa-thumbs-up"></i></a>
    {% else %}
      <a href="/like-post/{{post.id}}"><i class="far fa-thumbs-up"></i></a>
    {% endif %}
    {% if current_user == post.author %}
    <div class="btn-group d-inline-block d-flex">
            <button class="btn btn-sm btn-primary dropdown-toggle mx-auto" type="button" data-bs-toggle="dropdown">
            </button>
      <ul class="dropdown-menu">
        <li>
          <a
            class="btn btn-secondary btn-sm mr-1 mx-1 dropdown-item"
            href="{{ url_for('posts.update_post', post_id=post.id) }}"
          >
            Update
          </a>
        </li>
        <li>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger btn-sm mx-1 dropdown-item" type="submit" value="Delete">
          </form>
        </li>
      </ul>
    </div>
  {% endif %}

  <div class="container mt-5">
    <div class="row">
      <div class="col-md-12">
          <div class="card" style="margin-bottom: 20px;">
            <div class="container" style="width: 90%; max-width: 2500px; max-height: 1500px; overflow: hidden;">
                <br/>
                <img src="{{ url_for('static', filename='post_images/' + post.image_file) }}" width="100%" height="auto">
                <br/>
                <p>{{ post.content }}</p>
            </div>

            <div id="comments-{{post.id}}">
              <section class="card-body" id="comments-expanded-{{ post.id }}">
                {% for comment in post.comments %}
                  <hr>
                  <div class="d-flex w-100 mb-2">
                    <br />
                    <div style="overflow-wrap: break-word; width: calc(100% - 150px);">
                      <a href="{{ url_for('users.profile', username=post.author.username) }}">{{ comment.user.username }}</a>: {{ comment.content }}
                    </div>
                    <div class="pl-2" style="width: 150px; text-align: right;">
                      <div class="btn-group">
                        {% if current_user.id == comment.user_id %}
                          <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown"></button>
                            <ul class="dropdown-menu">
                              <li>
                                <a href="/delete-comment/{{comment.id}}" class="dropdown-item btn-sm">Delete</a>
                              </li>
                            </ul>
                          </div>
                        {% endif %} 
                        <div style="width: 120px; text-align: right;">
                          <small class="text-muted comment-date mt-1">
                            <time datetime="{{ comment.date_posted.strftime('%Y-%m-%dT%H:%M:%SZ') }}" format="%Y-%m-%d">{{ comment.date_posted.strftime('%Y-%m-%d') }}</time>
                          </small>
                        </div>
                      </div>
                    </div>
                  </div>
                  <br />
                {% endfor %}         
                <form method="POST" action="{{ url_for('posts.create_comment', post_id=post.id) }}" class="" >
                  {{ form.hidden_tag() }}
                  <div class="form-group">
                    {% if form.content.errors %}
                      {{ form.content(class="form-control is-invalid") }}
                      <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                          <span>{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% else %}
                      {{ form.content(class="form-control") }}
                    {% endif %}
                  </div>
                  <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                  </div>
                </form>
              </section>
            </div>




            
    
          </div>
      </div>
  </div>
  </div>


    

  
  <br />
</div>
</article>

{% endblock content %}

templates/search.html
{% extends "layout.html" %}
{% block content %}
<br><p style="padding: 10px;">Result for "{{ searched }}" ({{ users.count() }})</p>

{% for user in users %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card" style="margin-bottom: 20px">
                    <div class="card-header bg-primary text-while">
                        <img class="rounded-circle article-img img-fluid" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}">
                        <a class="mr-2 text-white" style="font-size: larger;" href="{{ url_for('users.profile', username=user.username) }}" width="200" height="200">{{ user.username }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>
{% endfor %}
{% endblock content %}